# -*- coding: utf-8 -*-
SQL = """
WITH D AS (
SELECT  PR.AREA_NAME,
        CAST (AREA_NB AS VARCHAR (10)) AS AREA_NUMBER,
        PR.ASSET_DESC,
        PR.CATEGORY_NAME,
        PR.START_DT,
        PR.ASSET_ID,
        PR.SERIAL_NB,
        PR.BARCODE_ID,
        CO.PROJECT_ID,
        CO.TEAM_NAME,
        CO.WAREHOUSE_NAME,
        CO.LOCATION_NAME
FROM    DB_A.DB_AREA_ASSETS PR
,       DB_INFO.DB_WAREHOUSE CO
WHERE   PR.AREA_NB = CO.WAREHOUSE_NUMBER
AND     PR.DIVISION_NAME = 'Division 123'
AND     PR.CATEGORY_NAME IN ('Vessel')
AND     TEAM_NAME <> 'TEAM_A'
AND     CO.TEAM_NAME != 'UNASSIGNED'
),
AVG_PRODUCT_A AS (
SELECT  PR.PROJECT_ID,
        SUM(PR.GROSS_PRODUCT_A_PROD) / 60 AVG_PRODUCT_A
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
MAX_PRODUCT_A AS (
SELECT  PR.PROJECT_ID,
        MAX(PR.GROSS_PRODUCT_A_PROD) MAX_PRODUCT_A
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
PRODUCT_A_FORECAST AS (
SELECT  PR.PROJECT_ID,
        PR.GROSS_FCST_PRODUCT_A_PROD PRODUCT_A_FORECAST
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate
and     PR.DATE_VALUE >= (sysdate - 2)
),
AVG_PRODUCT_B AS (
SELECT  PR.PROJECT_ID,
        SUM(PR.GROSS_PRODUCT_B_PROD) / 60 AVG_PRODUCT_B
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
MAX_PRODUCT_B AS (
SELECT  PR.PROJECT_ID,
        MAX(PR.GROSS_PRODUCT_B_PROD) MAX_PRODUCT_B
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
PRODUCT_B_FORECAST AS (
SELECT  PR.PROJECT_ID,
        PR.GROSS_FCST_PRODUCT_B_PROD PRODUCT_B_FORECAST
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate
and     PR.DATE_VALUE >= (sysdate - 2)
),
AVG_PRODUCT_C AS (
SELECT  PR.PROJECT_ID,
        SUM(PR.PRODUCT_C_PROD) / 60 AVG_PRODUCT_C
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
MAX_PRODUCT_C AS (
SELECT  PR.PROJECT_ID,
        MAX(PR.PRODUCT_C_PROD) MAX_PRODUCT_C
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate -1
and     PR.DATE_VALUE >= (sysdate - 61)
Group by PR.PROJECT_ID
),
PRODUCT_C_FORECAST AS (
SELECT  PR.PROJECT_ID,
        PR.GROSS_FCST_PRODUCT_C_PROD PRODUCT_C_FORECAST
FROM    DB_DBA.DB_COMP_PRODUCTION PR
WHERE   PR.DIVISION_ID = 000
and     PR.DATE_VALUE <= sysdate
and     PR.DATE_VALUE >= (sysdate - 2)
),
Manufacturer AS (
SELECT  Asset_id,
        ATTRIBUTE_VALUE AS Manufacturer
FROM    DB_A.ASSET_ATTRIBUTE_VALUES
WHERE   ATTRIBUTE_NAME = 'Manufacturer'
),
DIAMETER AS (
SELECT  Asset_id,
        ATTRIBUTE_VALUE AS Diameter
FROM    DB_A.ASSET_ATTRIBUTE_VALUES
WHERE   ATTRIBUTE_NAME = 'Diameter'
),
Orientation AS (
SELECT  Asset_id,
        ATTRIBUTE_VALUE AS Orientation
FROM    DB_A.ASSET_ATTRIBUTE_VALUES
WHERE   ATTRIBUTE_NAME = 'Orientation'
),
ELength AS (
SELECT  Asset_id, 
        ATTRIBUTE_VALUE AS EffectiveLength
FROM    DB_A.ASSET_ATTRIBUTE_VALUES
WHERE   ATTRIBUTE_NAME = 'Effective Length'
),
PR AS (
SELECT  Asset_id,
        ATTRIBUTE_VALUE AS PressureRating
FROM    DB_A.ASSET_ATTRIBUTE_VALUES
WHERE   ATTRIBUTE_NAME = 'Pressure Rating'
)
SELECT  AREA_NAME,
        AREA_NUMBER,
        TEAM_NAME,
        WAREHOUSE_NAME,
        LOCATION_NAME,
        AVG_PRODUCT_A,
        MAX_PRODUCT_A,
        PRODUCT_A_FORECAST,
        AVG_PRODUCT_B,
        MAX_PRODUCT_B,
        PRODUCT_B_FORECAST,
        AVG_PRODUCT_C,
        MAX_PRODUCT_C,
        PRODUCT_C_FORECAST,
        ASSET_DESC,
        BARCODE_ID, 
        SERIAL_NB,
        START_DT,
        CATEGORY_NAME,
        MANUFACTURER,
        ORIENTATION,
        EFFECTIVELENGTH,
        DIAMETER,
        PRESSURERATING
FROM    D
        LEFT JOIN AVG_PRODUCT_A ON D.PROJECT_ID = AVG_PRODUCT_A.PROJECT_ID
        LEFT JOIN MAX_PRODUCT_A ON D.PROJECT_ID = MAX_PRODUCT_A.PROJECT_ID
        LEFT JOIN PRODUCT_A_FORECAST ON D.PROJECT_ID = PRODUCT_A_FORECAST.PROJECT_ID
        LEFT JOIN AVG_PRODUCT_B ON D.PROJECT_ID = AVG_PRODUCT_B.PROJECT_ID
        LEFT JOIN MAX_PRODUCT_B ON D.PROJECT_ID = MAX_PRODUCT_B.PROJECT_ID
        LEFT JOIN PRODUCT_B_FORECAST ON D.PROJECT_ID = PRODUCT_B_FORECAST.PROJECT_ID
        LEFT JOIN AVG_PRODUCT_C ON D.PROJECT_ID = AVG_PRODUCT_C.PROJECT_ID
        LEFT JOIN MAX_PRODUCT_C ON D.PROJECT_ID = MAX_PRODUCT_C.PROJECT_ID
        LEFT JOIN PRODUCT_C_FORECAST ON D.PROJECT_ID = PRODUCT_C_FORECAST.PROJECT_ID
        LEFT JOIN DIAMETER ON D.Asset_id = DIAMETER.Asset_id
        LEFT JOIN Manufacturer ON D.Asset_id = Manufacturer.Asset_id
        LEFT JOIN Orientation ON D.Asset_id = Orientation.Asset_id
        LEFT JOIN ELength ON D.Asset_id = ELength.Asset_id
        LEFT JOIN PR ON D.Asset_id = PR.Asset_id
WHERE   EffectiveLength IS NOT NULL
ORDER BY AREA_NAME
"""
